import os

THRES_LOC_CANVAS = 0.98
THRES_LOC_CARDS = 0.9
THRES_PIXEL_CARD_NMS = 10

#PATH_CARD_TEMP_GLOB = './cards/*.jpeg'
#PATH_TOP_LEFT_CORNER = './topleft.jpeg'
#PATH_BTM_RIGHT_CORNER = './bottomright.jpeg'
PATH_CARD_TEMP_GLOB = './mumu_crop2/*.jpg'
PATH_TOP_LEFT_CORNER = './mumu_topleft.png'
PATH_BTM_RIGHT_CORNER = './mumu_bottomright.png'

NUM_CARDS_IN_ROW = 10
NUM_CARDS_IN_COL = 6

#CARD_WIDTH = 94
#CARD_HEIGHT = 128
#CARD_HALF_WIDTH = 47
#CARD_HALF_HEIGHT = 64

CARD_WIDTH = 113
CARD_HEIGHT = 152
CARD_HALF_WIDTH = 57
CARD_HALF_HEIGHT = 76

#
CARD_TYPE_CHARACTER_STR = "character"
CARD_TYPE_CIRCLE_STR = "circle"
CARD_TYPE_BAMBOO_STR = "bamboo"
CARD_TYPE_HONOR_STR = "honor"
CARD_TYPE_STRS = [
    CARD_TYPE_HONOR_STR,
    CARD_TYPE_CHARACTER_STR,
    CARD_TYPE_CIRCLE_STR,
    CARD_TYPE_BAMBOO_STR,
    ]

CARD_VALUE_ONE_STR = "one"
CARD_VALUE_TWO_STR = "two"
CARD_VALUE_THREE_STR = "three"
CARD_VALUE_FOUR_STR = "four"
CARD_VALUE_FIVE_STR = "five"
CARD_VALUE_SIX_STR = "six"
CARD_VALUE_SEVEN_STR = "seven"
CARD_VALUE_EIGHT_STR = "eight"
CARD_VALUE_NINE_STR = "nine"
CARD_VALUE_EAST_STR = "east"
CARD_VALUE_SOUTH_STR = "south"
CARD_VALUE_WEST_STR = "west"
CARD_VALUE_NORTH_STR = "north"
CARD_VALUE_RED_STR = "red"
CARD_VALUE_GREEN_STR = "green"
CARD_VALUE_WHITE_STR = "white"
CARD_VALUE_STRS = [
    CARD_VALUE_RED_STR,
    CARD_VALUE_GREEN_STR,
    CARD_VALUE_WHITE_STR,
    CARD_VALUE_EAST_STR,
    CARD_VALUE_SOUTH_STR,
    CARD_VALUE_WEST_STR,
    CARD_VALUE_NORTH_STR,
    CARD_VALUE_NINE_STR,
    CARD_VALUE_EIGHT_STR,
    CARD_VALUE_SEVEN_STR,
    CARD_VALUE_SIX_STR,
    CARD_VALUE_FIVE_STR,
    CARD_VALUE_FOUR_STR,
    CARD_VALUE_THREE_STR,
    CARD_VALUE_TWO_STR,
    CARD_VALUE_ONE_STR
    ]
CARD_SELECT_ORDER = ['{}_{}'.format(CARD_TYPE_STRS[0], v)
        for v in CARD_VALUE_STRS[:7]] + \
                [ '{}_{}'.format(t, v) for v in CARD_VALUE_STRS[7:]
                        for t in CARD_TYPE_STRS[1:]]

CARD_COST = {
    CARD_TYPE_CHARACTER_STR: {
        CARD_VALUE_ONE_STR: 1,
        CARD_VALUE_TWO_STR: 2,
        CARD_VALUE_THREE_STR: 3,
        CARD_VALUE_FOUR_STR: 4,
        CARD_VALUE_FIVE_STR: 5,
        CARD_VALUE_SIX_STR: 6,
        CARD_VALUE_SEVEN_STR: 7,
        CARD_VALUE_EIGHT_STR: 8,
        CARD_VALUE_NINE_STR: 9
        },
    CARD_TYPE_CIRCLE_STR: {
        CARD_VALUE_ONE_STR: 1,
        CARD_VALUE_TWO_STR: 2,
        CARD_VALUE_THREE_STR: 3,
        CARD_VALUE_FOUR_STR: 4,
        CARD_VALUE_FIVE_STR: 5,
        CARD_VALUE_SIX_STR: 6,
        CARD_VALUE_SEVEN_STR: 7,
        CARD_VALUE_EIGHT_STR: 8,
        CARD_VALUE_NINE_STR: 9
        },
    CARD_TYPE_BAMBOO_STR: {
        CARD_VALUE_ONE_STR: 1,
        CARD_VALUE_TWO_STR: 2,
        CARD_VALUE_THREE_STR: 3,
        CARD_VALUE_FOUR_STR: 4,
        CARD_VALUE_FIVE_STR: 5,
        CARD_VALUE_SIX_STR: 6,
        CARD_VALUE_SEVEN_STR: 7,
        CARD_VALUE_EIGHT_STR: 8,
        CARD_VALUE_NINE_STR: 9
        },
    CARD_TYPE_HONOR_STR: {
        CARD_VALUE_EAST_STR: 10,
        CARD_VALUE_SOUTH_STR: 10,
        CARD_VALUE_WEST_STR: 10,
        CARD_VALUE_NORTH_STR: 10,
        CARD_VALUE_RED_STR: 15,
        CARD_VALUE_GREEN_STR: 15,
        CARD_VALUE_WHITE_STR: 15
        }
    }
